/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\chain.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Torus009: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chain.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus009.geometry} material={materials['Material.001']} position={[-19, 0, -1]} rotation={[0.489, 0, 0]} scale={6.831} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[0, -27.6, 0]} scale={127.765} />
    </group>
  )
}

useGLTF.preload('/chain.glb')
